services:
  postgres:
    image: 'postgres:alpine'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'